blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='blog_index'),
    url(r'^detail/(?P<blog_id>[0-9]+)/$', views.detail, name='blog_detail'),
    url(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)$', views.archives, name='blog_archives'),
    url(r'^category/(?P<category_id>[0-9]+)/$', views.category, name='blog_category'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', views.tag, name='blog_tag'),
    url(r'^search/$', views.search, name='blog_search'),
]

website/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from blog.feed import LatestEntriesFeed
from blog import views as blog_views
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry

info_dict = {
    'queryset': Entry.objects.all(),
    'date_field': 'modified_time'
}

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^blog/', include('blog.urls', namespace='blog')),
                  url(r'^latest/feed/$', LatestEntriesFeed(), name='rss'),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},name='django.contraib.sitemaps.views.sitemap'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = blog_views.permission_denied
handler404 = blog_views.page_not_found
handler500 = blog_views.page_error

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128,verbose_name='博客分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = '博客分类'

class Tag(models.Model):
    name = models.CharField(max_length=128,verbose_name='博客标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = '博客标签'


class Entry(models.Model):
    title = models.CharField(max_length=128, verbose_name='文章标题')

    author = models.ForeignKey(User, verbose_name='博客作者')

    img = models.ImageField(upload_to='blog_images', null=True, blank=True)

    body = models.TextField(verbose_name='博客正文')

    abstract = models.TextField(max_length=256, blank=True, null=True,
                                verbose_name='博客摘要')
    visiting = models.PositiveIntegerField(default=0,verbose_name='博客访问量')

    category = models.ManyToManyField(Category, verbose_name='博客分类')

    tags = models.ManyToManyField(Tag, verbose_name='博客标签')

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    modified_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail',kwargs={'blog_id':self.id})

    def created_viting(self):
        self.visiting +=1
        self.save(update_fields=['visiting'])

    class Mate:
        # 添加索引排序
        ordering = ['-created_time']
        verbose_name = '博客'
        verbose_name_plural = '博客'

blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
import markdown
import pygments
from blog.utils.pager import Pagination
from django.db.models import Q


# Create your views here.


def index(request):
    page = request.GET.get('page', 1)
    total_count = models.Entry.objects.all().count()  #
    pager = Pagination(page, total_count, reverse('blog:blog_index'))
    depart_queryset = models.Entry.objects.all()[pager.start:pager.end]
    return render(request, 'blog/index.html', locals())


def detail(request, blog_id):
    entry = models.Entry.objects.get(id=blog_id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    entry.body = md.convert(entry.body)
    entry.toc = md.toc
    entry.created_viting()
    return render(request, 'blog/detail.html', locals())


def category(request, category_id):
    c = models.Category.objects.get(id=category_id)
    entries = models.Entry.objects.filter(category=c)
    page = request.GET.get('page', 1)
    total_count = entries.count()  #
    pager = Pagination(page, total_count, reverse('blog:blog_category', kwargs={"category_id": category_id}))
    depart_queryset = entries[pager.start:pager.end]
    return render(request, 'blog/index.html', locals())


def tag(request, tag_id):
    t = models.Tag.objects.get(id=tag_id)
    entries = models.Entry.objects.filter(tags=t)
    page = request.GET.get('page', 1)
    total_count = entries.count()  #
    pager = Pagination(page, total_count, reverse('blog:blog_tag', kwargs={'tag_id': tag_id}))
    depart_queryset = entries[pager.start:pager.end]
    return render(request, 'blog/index.html', locals())


def search(request):
    keyword = request.GET.get('keyword', None)
    if not keyword or str(keyword) == '':
        error_msg = "请输入关键字"
        # 跳转首页
        return redirect('blog:blog_index')

    entries = models.Entry.objects.filter(Q(title__icontains=keyword)
                                          | Q(body__icontains=keyword)
                                          | Q(abstract__icontains=keyword))
    page = request.GET.get('page', 1)
    total_count = entries.count()  #
    depart_queryset = entries
    return render(request, 'blog/index.html', locals())


def archives(request, year, month):
    entris = models.Entry.objects.filter(created_time__year=year, created_time__month=month)
    page = request.GET.get('page', 1)
    total_count = entris.count()  #
    pager = Pagination(page, total_count, reverse('blog:blog_archives', kwargs={'year': year, 'month': month}))
    depart_queryset = entris[pager.start:pager.end]
    return render(request, 'blog/index.html', locals())


def permission_denied(request):
    return redirect('blog/403.html', locals())


def page_not_found(request):
    return redirect('blog/404.html', locals())


def page_error(request):
    return redirect('blog/500.html', locals())

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap -->
    <link href={% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %} rel="stylesheet">
    <link href={% static 'blog/css/blog_nav.css' %} rel="stylesheet">
    {% block css %}
    {% endblock %}

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="{% static 'blog/image/logo_test.jpg' %}"/><span
                    class="navbar-text">我的博客</span></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/blog/">博客</a></li>
                <li><a href="#">关于博主</a></li>
                <li><a href="#">联系我们</a></li>
                <li><a href="#">友情链接</a></li>
            </ul>
            <form class="navbar-form navbar-left" action="{% url "blog:blog_search" %}" method=" get
            ">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search" name="keyword">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>{{ request.session.screen_name }}<a href="">
                    <i class="glyphicon glyphicon-log-out"></i>注销</a></li>
                <li>
                    <a href="">
                        <i class="glyphicon glyphicon-log-in"></i>&nbsp;&nbsp;登录</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% block content %}
{% endblock %}

<footer>
    <div class="footer" role="navigation">
        <div class="container">
            <div class="navbar-text">
                <ul class="footer-text">
                    <li><a href="#">主页</a></li>
                    <li><a href="#">联系我们</a></li>
                    <li><a href="#">关于博主</a></li>
                    <li><a href="#">文档支持</a></li>
                    <li><a href="/blog/">博客首页</a></li>
                </ul>
                <p>Copyright © 2018 安宇x的博客</p>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/github.css' %}">
{% endblock %}


{% block content %}
    <div class="container" style="margin-top: 50px">
        <div class="row">
            <div class="col-md-9">
                <h2>{{ entry.title }}</h2>
                <div>
                    <p>
                        <span>作者:{{ entry.author }}</span>
                        <span>发表时间:{{ entry.created_time }}</span>
                        <span>浏览量:{{ entry.visiting }}</span>
                        分类：
                        {% for category in entry.category.all %}
                            &nbsp;&nbsp;<a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                        {% endfor %}
                        标签：
                        {% for tag in entry.tags.all %}
                            &nbsp;&nbsp;<a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
                        {% endfor %}
                    </p>
                </div>
                <div>
                    {% if entry.img %}
                        <img src="{{ entry.img.url }}" alt="{{ entry.title }}" style="max-width: 100%">
                    {% endif %}
                </div>
                <div>
                    {{ entry.toc|safe }}
                    {{ entry.body|safe }}
                </div>
            </div>
            <div class="col-md-3">
                {% include 'blog/right_side_bar.html' %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
    博客首页
{% endblock %}

{% block css %}

{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% for entry in depart_queryset %}
                    <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2>
                    <div>
                        {% if entry.img %}
                            <img src="{{ entry.img.url }}" alt="{{ entry.title }}" width="100">
                        {% endif %}
                    </div>
                    <div>
                        {% if entry.abstract %}
                            <p>{{ entry.abstract }}</p>
                        {% else %}
                            <p>{{ entry.body | truncatechars:64 }}</p>
                        {% endif %}

                        <p>
                            <span>作者:{{ entry.author }}</span>
                            <span>发表时间:{{ entry.created_time }}</span>
                            <span>浏览量:{{ entry.visiting }}</span>
                        </p>
                    </div>
                {% endfor %}
                <hr>
                <ul class="pagination">
                    {{ pager.page_html|safe }}
                </ul>
            </div>
            <div class="col-md-3">
                {% include 'blog/right_side_bar.html' %}
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}

{% endblock %}

blog/templates/blog/right_side_bar.html
{% load blog_tags %}
<div class="row">
    <div class="widget">
        <h3>最新博客：</h3>
        {% get_recent_entries as recent_entry_list %}

        {% for entry in recent_entry_list %}
            <div>
                <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                <div>{{ entry.author }} 发表于： {{ entry.created_time|date:"Y年m月d日" }}</div>
            </div>
        {% endfor %}

    </div>
</div>

<hr>


<div class="row">
    <div class="widget">
        <h3>推荐博客：</h3>
        {% get_popular_entries as recent_popular_list %}

        {% for popular in recent_popular_list %}
            <div>
                <a href="{{ popular.get_absolute_url }}">{{ popular.title }}</a>
                <span class="badge" style="color: #fff; background-color: #00bfff">{{ popular.visiting }}</span>
            </div>
        {% endfor %}

    </div>
</div>

<hr>

<div class="row">
    <div class="widget">
        <h3>博客分类：</h3>
        {% get_categories as category_list %}
        <ul class="list-group">
        {% for category in category_list %}
            <li class="list-group-item">
                <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                <span class="badge">{% get_entry_of_category category.name %}</span>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>


<hr>
<div class="row">
    <div class="widget">
        <h3>归档：</h3>
        {% archives as date_list %}
        <ul class="list-group">
        {% for date in date_list %}
            <li class="list-group-item">
                <a href="{% url 'blog:blog_archives' date.year date.month %}">
                    <i class="glyphicon glyphicon-chevron-right"></i>
                    {{ date.year }}年{{ date.month }}月
                    <span class="badge">{% get_entry_count_of_date date.year date.month %}</span>
                </a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>


<hr>
<div class="row">
    <div class="widget">
        <h3>云标签：</h3>
        {% get_tags as tags_list %}
        <ul class="list-group">
        {% for tag in tags_list %}
                <a href="{% url 'blog:blog_tag' tag.id %}" class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warn' %}">{{ tag.name }}</a>
        {% endfor %}
        </ul>
    </div>
</div>

<hr>
<div class="row">
    <div class="rss">
        <a href="{% url 'rss' %}"> <i class="glyphicon glyphicon-globe">RSS</i>订阅 </a>
    </div>
</div>